### Import Libraries

In [131]:
import numpy as np
import pandas as pd

from sklearn.preprocessing import LabelEncoder

### Import Data

In [132]:
pd.options.display.max_columns = None

dataset = pd.read_csv('hotel_bookings.csv')
dataset.head()

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,country,market_segment,distribution_channel,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,reserved_room_type,assigned_room_type,booking_changes,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,C,C,3,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,C,C,4,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,0.0,0,BB,GBR,Direct,Direct,0,0,0,A,C,0,No Deposit,NaN,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,0.0,0,BB,GBR,Corporate,Corporate,0,0,0,A,A,0,No Deposit,304.0,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,NaN,0,Transient,98.0,0,1,Check-Out,2015-07-03

In [133]:
df = dataset.copy()

In [134]:
df.isnull().sum().sort_values(ascending=False)

company                           112593
agent                              16340
country                              488
children                               4
reserved_room_type                     0
assigned_room_type                     0
booking_changes                        0
deposit_type                           0
hotel                                  0
previous_cancellations                 0
days_in_waiting_list                   0
customer_type                          0
adr                                    0
required_car_parking_spaces            0
total_of_special_requests              0
reservation_status                     0
previous_bookings_not_canceled         0
is_repeated_guest                      0
is_canceled                            0
distribution_channel                   0
market_segment                         0
meal                                   0
babies                                 0
adults                                 0
stays_in_week_nights                   0
stays_in_weekend_nights                0
arrival_date_day_of_month              0
arrival_date_week_number               0
arrival_date_month                     0
arrival_date_year                      0
lead_time                              0
reservation_status_date                0
dtype: int64

In [135]:
df[['agent', 'company']] = df[['agent', 'company']].fillna(0.0)

In [136]:
df['country'].fillna(dataset.country.mode().to_string(), inplace=True)

In [137]:
df['children'].fillna(round(dataset.children.mean()), inplace=True)

In [138]:
df = df.drop(df[(df.adults+df.babies+df.children)==0].index)

In [139]:
df.isnull().sum().sort_values(ascending=False)

hotel                             0
is_canceled                       0
reservation_status                0
total_of_special_requests         0
required_car_parking_spaces       0
adr                               0
customer_type                     0
days_in_waiting_list              0
company                           0
agent                             0
deposit_type                      0
booking_changes                   0
assigned_room_type                0
reserved_room_type                0
previous_bookings_not_canceled    0
previous_cancellations            0
is_repeated_guest                 0
distribution_channel              0
market_segment                    0
country                           0
meal                              0
babies                            0
children                          0
adults                            0
stays_in_week_nights              0
stays_in_weekend_nights           0
arrival_date_day_of_month         0
arrival_date_week_number          0
arrival_date_month                0
arrival_date_year                 0
lead_time                         0
reservation_status_date           0
dtype: int64

In [140]:
df.dtypes

hotel                              object
is_canceled                         int64
lead_time                           int64
arrival_date_year                   int64
arrival_date_month                 object
arrival_date_week_number            int64
arrival_date_day_of_month           int64
stays_in_weekend_nights             int64
stays_in_week_nights                int64
adults                              int64
children                          float64
babies                              int64
meal                               object
country                            object
market_segment                     object
distribution_channel               object
is_repeated_guest                   int64
previous_cancellations              int64
previous_bookings_not_canceled      int64
reserved_room_type                 object
assigned_room_type                 object
booking_changes                     int64
deposit_type                       object
agent                             float64
company                           float64
days_in_waiting_list                int64
customer_type                      object
adr                               float64
required_car_parking_spaces         int64
total_of_special_requests           int64
reservation_status                 object
reservation_status_date            object
dtype: object

In [141]:
df[['children', 'company', 'agent']] = df[['children', 'company', 'agent']].astype('int64')

In [142]:
df.head()

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,country,market_segment,distribution_channel,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,reserved_room_type,assigned_room_type,booking_changes,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,0,0,BB,PRT,Direct,Direct,0,0,0,C,C,3,No Deposit,0,0,0,Transient,0.0,0,0,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,0,0,BB,PRT,Direct,Direct,0,0,0,C,C,4,No Deposit,0,0,0,Transient,0.0,0,0,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,0,0,BB,GBR,Direct,Direct,0,0,0,A,C,0,No Deposit,0,0,0,Transient,75.0,0,0,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,0,0,BB,GBR,Corporate,Corporate,0,0,0,A,A,0,No Deposit,304,0,0,Transient,75.0,0,0,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240,0,0,Transient,98.0,0,1,Check-Out,2015-07-03

In [143]:
df_cleaned = df.copy()


df_cleaned['room'] = 0
df_cleaned.loc[df_cleaned['reserved_room_type'] == df_cleaned['assigned_room_type'] , 'room'] = 1

df_cleaned['net_cancelled'] = 0
df_cleaned.loc[df_cleaned['previous_cancellations'] > df_cleaned['previous_bookings_not_canceled'] , 'net_cancelled'] = 1

df_cleaned = df_cleaned.drop(['reservation_status','arrival_date_year','arrival_date_week_number','arrival_date_day_of_month',
                            'arrival_date_month','assigned_room_type','reserved_room_type','reservation_status_date',
                            'previous_cancellations','previous_bookings_not_canceled'],axis=1)

In [144]:
df_cleaned[df_cleaned['country'] == 'PRT'].count()

hotel                          48483
is_canceled                    48483
lead_time                      48483
stays_in_weekend_nights        48483
stays_in_week_nights           48483
adults                         48483
children                       48483
babies                         48483
meal                           48483
country                        48483
market_segment                 48483
distribution_channel           48483
is_repeated_guest              48483
booking_changes                48483
deposit_type                   48483
agent                          48483
company                        48483
days_in_waiting_list           48483
customer_type                  48483
adr                            48483
required_car_parking_spaces    48483
total_of_special_requests      48483
room                           48483
net_cancelled                  48483
dtype: int64

In [145]:
df_cleaned[df_cleaned['country'] == '0    PRT'].count()

hotel                          478
is_canceled                    478
lead_time                      478
stays_in_weekend_nights        478
stays_in_week_nights           478
adults                         478
children                       478
babies                         478
meal                           478
country                        478
market_segment                 478
distribution_channel           478
is_repeated_guest              478
booking_changes                478
deposit_type                   478
agent                          478
company                        478
days_in_waiting_list           478
customer_type                  478
adr                            478
required_car_parking_spaces    478
total_of_special_requests      478
room                           478
net_cancelled                  478
dtype: int64

In [146]:
df_cleaned.loc[df_cleaned['country'] == '0    PRT' , 'country'] = 'PRT'

In [147]:
df_cleaned[df_cleaned['country'] == 'PRT'].count()

hotel                          48961
is_canceled                    48961
lead_time                      48961
stays_in_weekend_nights        48961
stays_in_week_nights           48961
adults                         48961
children                       48961
babies                         48961
meal                           48961
country                        48961
market_segment                 48961
distribution_channel           48961
is_repeated_guest              48961
booking_changes                48961
deposit_type                   48961
agent                          48961
company                        48961
days_in_waiting_list           48961
customer_type                  48961
adr                            48961
required_car_parking_spaces    48961
total_of_special_requests      48961
room                           48961
net_cancelled                  48961
dtype: int64

In [148]:
df_cleaned[df_cleaned['country'] == '0    PRT'].count()

hotel                          0
is_canceled                    0
lead_time                      0
stays_in_weekend_nights        0
stays_in_week_nights           0
adults                         0
children                       0
babies                         0
meal                           0
country                        0
market_segment                 0
distribution_channel           0
is_repeated_guest              0
booking_changes                0
deposit_type                   0
agent                          0
company                        0
days_in_waiting_list           0
customer_type                  0
adr                            0
required_car_parking_spaces    0
total_of_special_requests      0
room                           0
net_cancelled                  0
dtype: int64

In [149]:
#Export Cleaned DataFrame to a CSV file
df_cleaned.to_csv (r'hotel_bookings_clean.csv', index = False, header=True)

In [150]:
print(df_cleaned.columns)
df_cleaned.head()

Index(['hotel', 'is_canceled', 'lead_time', 'stays_in_weekend_nights',
       'stays_in_week_nights', 'adults', 'children', 'babies', 'meal',
       'country', 'market_segment', 'distribution_channel',
       'is_repeated_guest', 'booking_changes', 'deposit_type', 'agent',
       'company', 'days_in_waiting_list', 'customer_type', 'adr',
       'required_car_parking_spaces', 'total_of_special_requests', 'room',
       'net_cancelled'],
      dtype='object')

,hotel,is_canceled,lead_time,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,country,market_segment,distribution_channel,is_repeated_guest,booking_changes,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,room,net_cancelled
0,Resort Hotel,0,342,0,0,2,0,0,BB,PRT,Direct,Direct,0,3,No Deposit,0,0,0,Transient,0.0,0,0,1,0
1,Resort Hotel,0,737,0,0,2,0,0,BB,PRT,Direct,Direct,0,4,No Deposit,0,0,0,Transient,0.0,0,0,1,0
2,Resort Hotel,0,7,0,1,1,0,0,BB,GBR,Direct,Direct,0,0,No Deposit,0,0,0,Transient,75.0,0,0,0,0
3,Resort Hotel,0,13,0,1,1,0,0,BB,GBR,Corporate,Corporate,0,0,No Deposit,304,0,0,Transient,75.0,0,0,1,0
4,Resort Hotel,0,14,0,2,2,0,0,BB,GBR,Online TA,TA/TO,0,0,No Deposit,240,0,0,Transient,98.0,0,1,1,0

In [151]:
def transform(dataframe):
    
    le = LabelEncoder()    
    categorical_features = list(dataframe.columns[dataframe.dtypes == object])    
    
    return dataframe[categorical_features].apply(lambda x: le.fit_transform(x))

df_cleaned_t = df_cleaned.copy()
df_cleaned_t = transform(df_cleaned_t)
df_cleaned[['hotel', 'meal', 'country', 'market_segment', 'distribution_channel', 'deposit_type', 'customer_type']] = df_cleaned_t[['hotel', 'meal', 'country', 'market_segment', 'distribution_channel', 'deposit_type', 'customer_type']]
df_cleaned.head()

,hotel,is_canceled,lead_time,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,country,market_segment,distribution_channel,is_repeated_guest,booking_changes,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,room,net_cancelled
0,1,0,342,0,0,2,0,0,0,135,3,1,0,3,0,0,0,0,2,0.0,0,0,1,0
1,1,0,737,0,0,2,0,0,0,135,3,1,0,4,0,0,0,0,2,0.0,0,0,1,0
2,1,0,7,0,1,1,0,0,0,59,3,1,0,0,0,0,0,0,2,75.0,0,0,0,0
3,1,0,13,0,1,1,0,0,0,59,2,0,0,0,0,304,0,0,2,75.0,0,0,1,0
4,1,0,14,0,2,2,0,0,0,59,6,3,0,0,0,240,0,0,2,98.0,0,1,1,0